# Пользователи
## Создать нового пользователя

POST http://localhost:3003/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "megatomatos@gmail.com",
  "avatarPath": "tomatos.png",
  "name": "Tomato",
  "password": "tomatoma"
}

###


## Авторизовать пользователя

POST http://localhost:3003/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "megatomatos@gmail.com",
  "password": "tomatoma"
}

###

## Отправить изображение

POST http://localhost:3003/users/6542c25525a9a0acd48f4956/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="robot.png"
Content-Type: image/png

< /home/nikita/pet_projects/2420425-six-cities-5/robot.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверка авторизации пользователя
GET http://localhost:3003/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1lZ2F0b21hdG9zQGdtYWlsLmNvbSIsIm5hbWUiOiJUb21hdG8iLCJpZCI6IjY1NTEwYjU3NzUwYzc0YTE0YTM1ODJhNiIsImlhdCI6MTY5OTgxMDI1MSwiZXhwIjoxNjk5OTgzMDUxfQ.8fwMhiZi81s6ahOBsCEf5SayeCU_q0ocN8ZK4PXt73A

###
