export const DEFAULT_OFFER_COUNT = 25;
export const DEFAULT_DISCUSSED_OFFER_COUNT = 5;
export const DEFAULT_NEW_OFFER_COUNT = 5;
export const DEFAULT_FAVORITE_OFFER_COUNT = 5;
export const DEFAULT_PREMIUM_OFFER_COUNT = 3;
