# Категории
## Получить список удобств
GET http://localhost:3003/amenities HTTP/1.1

###

## Список объявлений с определёнными удобствами

GET http://localhost:3003/amenities/6550ed7db585005ec7ff463d/offers?limit=4 HTTP/1.1

###
