export enum Component {
  Config = 'Config',
  Logger = 'Logger',
  RestApplication = 'RestApplication',
  DatabaseClient = 'DatabaseClient',
  UserService = 'UserService',
  UserModel = 'UserModel',
  UserController = 'UserController',
  OfferModel = 'OfferModel',
  OfferService = 'OfferService',
  OfferController = 'OfferController',
  AmenityModel = 'AmenityModel',
  AmenityService = 'AmenityService',
  AmenityController = 'AmenityController',
  CommentService = 'CommentService',
  CommentModel = 'CommentModel',
  CommentController = 'CommentController',
  ExceptionFilter = 'ExceptionFilter',
  AuthService = 'AuthService',
  AuthExceptionFilter = 'AuthExceptionFilter',
  CityModel = 'CityModel',
  CityService = 'CityService',
  CityController = 'CityController',
}
