export enum Component {
  Config = 'Config',
  Logger = 'Logger',
  RestApplication = 'RestApplication',
  DatabaseClient = 'DatabaseClient',
  UserService = 'UserService',
  UserModel = 'UserModel',
  UserController = 'UserController',
  OfferModel = 'OfferModel',
  OfferService = 'OfferService',
  AmenityModel = 'AmenityModel',
  AmenityService = 'AmenityService',
  AmenityController = 'AmenityController',
  CommentService = 'CommentService',
  CommentModel = 'CommentModel',
  ExceptionFilter = 'ExceptionFilter',
}
